# -*- coding: utf-8 -*-
"""
CHEONOK Social Signal Scout v0.3 Analyzer
-----------------------------------------
Purpose:
- Read one Social Signal Scout workdir generated by v0.2 or Universal Reader.
- Convert metadata/subtitles/transcript into CHEONOK strategy outputs.
- Rule-based analyzer with category classification.

Important patch:
- Do not force every AI/YouTube signal into "faceless YouTube".
- Classify first, then generate category-specific report.

Usage:
python tools/social_signal_scout_v03_analyze.py "C:/Users/USER/Desktop/CHEONOK_SOCIAL_SCOUT/data/social_signal_scout/WORKDIR"

Output:
- content_ideas.md
"""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime
from pathlib import Path


def read_text(path: Path, limit: int = 70000) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")[:limit]


def load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8", errors="replace"))
    except Exception:
        return {}


def clean_text(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def extract_hashtags(text: str):
    return sorted(set(re.findall(r"#[A-Za-z0-9_가-힣]+", text or "")))


def has_any(low: str, keys: list[str]) -> bool:
    return any(k in low for k in keys)


def detect_signals(text: str):
    low = (text or "").lower()
    rules = [
        ("AI/자동화", ["ai", "a.i", "automation", "automate", "자동화", "인공지능", "agent", "에이전트"]),
        ("AI 에이전트/런타임", ["claude code", "cursor", "coding agent", "ai agent", "agentic", "코딩 도구", "코드 수정", "충돌", "오류", "백그라운드", "5분마다", "작은 ai", "수천개", "에이전트"]),
        ("작은 팀/레버리지", ["small team", "solo", "one person", "1 person", "founder", "startup", "작은 팀", "혼자", "스타트업", "큰 회사", "정면으로 이기는"]),
        ("불편함/문제 해결", ["pain", "problem", "friction", "불편", "문제", "귀찮", "힘들", "못 따라가는", "해결"]),
        ("현금흐름/수익", ["money", "revenue", "income", "earn", "수익", "돈", "매출", "달러", "$"]),
        ("얼굴 없는 콘텐츠", ["faceless", "no face", "without showing", "얼굴 없이", "얼굴 안", "비대면"]),
        ("유튜브/쇼츠", ["youtube", "shorts", "short", "유튜브", "쇼츠"]),
        ("니치/포맷", ["niche", "니치", "micro niche", "format", "포맷"]),
        ("초보자/쉬움", ["beginner", "easy", "simple", "초보", "쉽게", "편집 없이", "without editing"]),
        ("빠른 시간/단기 성과", ["90 days", "30 days", "in a day", "하루", "90일", "30일", "fast", "quick"]),
        ("도구/소프트웨어", ["tool", "software", "app", "github", "open source", "도구", "프로그램", "앱"]),
        ("역추적/성공 시스템", ["copy", "clone", "proven", "successful", "성공한", "복제", "2등", "3등", "역추적"]),
    ]
    found = []
    for name, keys in rules:
        if has_any(low, keys):
            found.append(name)
    return found


def classify_category(text: str, signals: list[str]) -> tuple[str, str]:
    low = (text or "").lower()

    if "AI 에이전트/런타임" in signals or has_any(low, ["claude code", "coding agent", "코딩 도구", "코드 수정", "백그라운드", "5분마다", "충돌", "오류"]):
        return "AI_AGENT_RUNTIME", "AI 에이전트/런타임/작은 팀 레버리지"

    if "역추적/성공 시스템" in signals:
        return "PROVEN_SYSTEM_REVERSE", "성공 시스템 역추적/2등·3등 전략"

    if "얼굴 없는 콘텐츠" in signals or ("유튜브/쇼츠" in signals and "니치/포맷" in signals and ("현금흐름/수익" in signals or "초보자/쉬움" in signals)):
        return "FACELESS_CONTENT_ENGINE", "얼굴 없는 콘텐츠/유튜브 니치"

    if "불편함/문제 해결" in signals:
        return "PAIN_TO_PRODUCT", "불편함 해소/상품화"

    if "도구/소프트웨어" in signals and "AI/자동화" in signals:
        return "TOOL_DISCOVERY", "AI 도구/소프트웨어 발견"

    if "현금흐름/수익" in signals:
        return "MONEY_SIGNAL", "수익화/현금흐름 신호"

    return "GENERAL_SOCIAL_SIGNAL", "일반 소셜 신호"


def infer_desires(category: str, signals: list[str]):
    if category == "AI_AGENT_RUNTIME":
        return [
            "직접 일하지 않고 AI에게 병렬로 일을 시키고 싶다",
            "작은 팀이나 1인도 큰 조직처럼 움직이고 싶다",
            "오류 수정·충돌 수습·피드백 분석 같은 반복 작업을 자동화하고 싶다",
            "휴대폰이나 간단한 지시만으로 운영체계가 돌아가길 원한다",
            "AI 시대에 뒤처지지 않고 더 빠르게 실행하고 싶다",
        ]
    if category == "PROVEN_SYSTEM_REVERSE":
        return [
            "이미 성공한 시스템을 찾아 실패 확률을 줄이고 싶다",
            "0에서 새로 만들기보다 검증된 구조를 더 쉽게 재구성하고 싶다",
            "2등·3등 포지션으로 빠르게 시장에 진입하고 싶다",
        ]
    if category == "PAIN_TO_PRODUCT":
        return [
            "반복되는 불편함을 즉시 해결하고 싶다",
            "사소한 귀찮음을 줄여 시간과 판단 피로를 아끼고 싶다",
            "불편함을 해결하는 간단한 상품에 돈을 지불할 의향이 있다",
        ]
    desires = []
    if "현금흐름/수익" in signals:
        desires.append("지금 돈이 도는 구조를 만들고 싶다")
    if "얼굴 없는 콘텐츠" in signals:
        desires.append("얼굴을 드러내지 않고도 콘텐츠 자산을 만들고 싶다")
    if "유튜브/쇼츠" in signals:
        desires.append("플랫폼 추천 알고리즘을 타고 반복 유입을 만들고 싶다")
    if "AI/자동화" in signals:
        desires.append("사람이 직접 다 하지 않고 AI로 시간을 줄이고 싶다")
    if "니치/포맷" in signals:
        desires.append("경쟁이 덜한 작은 시장과 반복 포맷을 찾고 싶다")
    if "초보자/쉬움" in signals:
        desires.append("복잡한 기술 없이 바로 시작하고 싶다")
    if not desires:
        desires.append("새로운 기회가 있는지 확인하고 싶다")
    return desires


def risk_flags(category: str, text: str):
    low = (text or "").lower()
    risks = []
    if category == "AI_AGENT_RUNTIME":
        risks.extend([
            "영상 속 사례가 특정 개인/회사 환경에 의존할 수 있으므로 그대로 재현 가능하다고 보면 위험",
            "AI 에이전트 병렬 작업은 오류·보안·충돌·비용 관리가 없으면 오히려 업무를 망칠 수 있음",
            "핵심은 도구 이름이 아니라 반복 루프·검증·롤백·보고 구조임",
        ])
    if category == "PROVEN_SYSTEM_REVERSE":
        risks.extend([
            "성공 시스템의 겉모습·문구·상표를 복제하면 법적/브랜드 위험이 있음",
            "복제할 것은 디자인이 아니라 불편함 해결 구조·유입 구조·결제 구조임",
        ])
    if any(k in low for k in ["$", "달러", "revenue", "income", "수익"]):
        risks.append("수익 인증은 과장 가능성이 있으므로 증거로 쓰지 말고 신호로만 사용")
    if any(k in low for k in ["one tool", "도구 하나", "without editing", "편집 없이"]):
        risks.append("도구 하나로 해결된다는 표현은 과장일 수 있음")
    if any(k in low for k in ["faceless", "얼굴 없이", "얼굴 안"]):
        risks.append("얼굴 없는 콘텐츠는 니치·대본·유지력이 핵심이며 자동화만으로는 부족")
    if not risks:
        risks.append("원본 콘텐츠의 맥락과 저작권을 확인해야 함")
    return risks


def category_interpretation(category: str):
    if category == "AI_AGENT_RUNTIME":
        return """이 콘텐츠의 본질은 단순히 \"AI 코딩 도구가 좋다\"가 아니다.
본질은 사람이 직접 모든 코드를 치는 구조에서 벗어나,
AI 에이전트들에게 병렬로 일을 맡기고,
오류·충돌·피드백·반복 수정까지 백그라운드 루프로 돌리는 운영체계다.

CHEONOK은 이것을 \"도구 추천\"으로 소비하지 않고,
대표는 방향을 정하고 시스템은 수집·분석·수정·보고를 반복하는 Runtime 구조로 흡수한다."""
    if category == "PROVEN_SYSTEM_REVERSE":
        return """이 콘텐츠의 본질은 베끼기가 아니다.
본질은 이미 돈을 번 시스템에서 검증된 불편함·고객·가격·유입·결제 구조를 역추적하고,
더 쉽고 더 인간친화적인 2등·3등 포지션으로 재구성하는 것이다.

CHEONOK은 겉모습을 복사하지 않고 작동 원리와 불편함 해결 구조를 복제·개선한다."""
    if category == "PAIN_TO_PRODUCT":
        return """이 콘텐츠의 본질은 불편함이다.
사람들은 반복되는 귀찮음, 판단 피로, 시간 낭비를 줄여주는 해결책에 돈을 낸다.
CHEONOK은 신호를 볼 때 먼저 '무엇이 불편한가'를 찾고, 행동 수를 줄이는 상품 구조로 바꾼다."""
    if category == "FACELESS_CONTENT_ENGINE":
        return """이 콘텐츠의 본질은 단순히 \"AI 도구 하나로 돈 벌기\"가 아니다.
본질은 얼굴을 드러내지 않아도, 복잡한 편집을 몰라도,
AI와 니치 전략을 통해 콘텐츠 자산을 만들고 싶은 욕망이다.

CHEONOK은 이것을 과장 수익 메시지로 쓰지 않고,
성실하지만 도구가 부족한 사람이 유입·콘텐츠·결제·보고 구조를 갖추도록 돕는 방향으로 변환한다."""
    return """이 콘텐츠는 대중이 저장·공유·반응하는 신호로 본다.
CHEONOK은 이를 그대로 베끼지 않고,
불편함 해소·현실 현금흐름·콘텐츠 유입·사람 가치 증폭 구조로 변환한다."""


def content_ideas(category: str):
    if category == "AI_AGENT_RUNTIME":
        return [
            "AI 에이전트가 일하게 만드는 운영체계의 핵심",
            "작은 팀이 큰 회사를 이기는 방식: 사람이 아니라 Runtime이 일한다",
            "Claude Code식 작업법을 CHEONOK Runtime으로 번역하면 무엇이 되는가",
            "직접 코딩보다 중요한 것: 지시·검증·롤백·보고 루프",
            "AI 시대에 뒤처지는 회사와 빨라지는 회사의 차이",
        ]
    if category == "PROVEN_SYSTEM_REVERSE":
        return [
            "이미 성공한 시스템을 역추적하는 법",
            "2등·3등 전략이 실패 확률을 줄이는 이유",
            "겉모습 복제가 아니라 구조 복제가 돈이 되는 이유",
            "성공 사례에서 불편함·가격·유입 구조를 뽑는 체크리스트",
            "CHEONOK Reverse Market Scout가 필요한 이유",
        ]
    if category == "PAIN_TO_PRODUCT":
        return [
            "사람들은 불편함이 사라지면 돈을 낸다",
            "신발끈 같은 작은 불편함이 큰 시장이 되는 이유",
            "좋은 사업 아이템은 거창한 기술보다 반복되는 귀찮음에서 나온다",
            "행동 수를 줄이면 상품 가치가 올라간다",
            "불편함을 상품으로 바꾸는 CHEONOK 공식",
        ]
    if category == "FACELESS_CONTENT_ENGINE":
        return [
            "얼굴 없이도 시작할 수 있는 콘텐츠 사업의 진짜 핵심",
            "AI 유튜브 자동화가 실패하는 이유",
            "도구 하나보다 중요한 것은 니치와 반복 포맷이다",
            "혼자 일하는 사람이 콘텐츠 자산을 만드는 법",
            "성실하지만 도구가 없는 사람을 위한 운영 구조",
        ]
    return [
        "이 신호에서 드러난 불편함을 해결하는 방법",
        "사람들이 이 콘텐츠에 반응한 이유",
        "CHEONOK은 이 신호를 어떤 상품으로 바꿀 수 있는가",
        "반복되는 신호를 데이터베이스화해야 하는 이유",
        "오늘 발견한 신호를 내일 실행으로 바꾸는 법",
    ]


def make_shorts_scripts(category: str):
    if category == "AI_AGENT_RUNTIME":
        return [
            {
                "title": "AI 시대, 진짜 중요한 건 도구가 아니라 운영체계입니다",
                "hook": "AI 코딩 도구를 잘 쓰는 사람은 코드를 덜 칩니다.",
                "body": "중요한 건 AI에게 일을 병렬로 맡기고, 오류와 충돌을 자동으로 잡고, 결과를 보고받는 루프입니다. 작은 팀이 큰 회사를 이기는 핵심은 도구가 아니라 Runtime입니다.",
                "cta": "CHEONOK은 이런 작업 방식을 현실 운영체계로 바꿉니다.",
            },
            {
                "title": "작은 팀이 큰 회사를 이기는 시대",
                "hook": "앞으로 이기는 팀은 사람이 많은 팀이 아닐 수 있습니다.",
                "body": "AI 에이전트가 반복 작업을 처리하고, 사람은 방향과 판단만 맡는 구조가 오고 있습니다. 지금 필요한 건 AI를 많이 쓰는 게 아니라 AI가 일하는 구조를 만드는 겁니다.",
                "cta": "반복 업무부터 Runtime으로 바꾸는 게 시작입니다.",
            },
            {
                "title": "AI에게 일을 맡길 때 반드시 필요한 것",
                "hook": "AI한테 시키면 끝이라고 생각하면 위험합니다.",
                "body": "지시, 검증, 오류 수정, 충돌 수습, 보고서가 한 루프로 묶여야 합니다. 이것이 없으면 자동화가 아니라 혼란입니다.",
                "cta": "CHEONOK은 자동화보다 먼저 검증 루프를 만듭니다.",
            },
        ]
    if category == "PROVEN_SYSTEM_REVERSE":
        return [
            {
                "title": "0에서 시작하지 말고 이미 성공한 시스템을 역추적하세요",
                "hook": "완전히 새로운 아이템을 만들려고 하면 실패 확률이 높습니다.",
                "body": "이미 돈을 번 시스템에는 검증된 불편함, 고객, 가격, 유입 구조가 있습니다. 베끼는 게 아니라 작동 원리를 분석해 더 쉬운 버전으로 재구성하는 겁니다.",
                "cta": "CHEONOK은 성공 구조를 역추적해 실행 가능한 MVP로 바꿉니다.",
            }
        ]
    if category == "PAIN_TO_PRODUCT":
        return [
            {
                "title": "사람들은 불편함이 사라지면 돈을 냅니다",
                "hook": "좋은 사업 아이템은 거창한 기술보다 작은 귀찮음에서 시작됩니다.",
                "body": "반복되는 불편함을 찾고, 행동 수를 줄이고, 바로 쓸 수 있게 만들면 사람은 돈을 냅니다. 신발끈도, 자동화도, 좋은 앱도 본질은 같습니다.",
                "cta": "CHEONOK은 불편함을 상품 구조로 바꿉니다.",
            }
        ]
    return [
        {
            "title": "얼굴 없이 돈 버는 콘텐츠, 진짜 핵심은 AI가 아닙니다",
            "hook": "얼굴 안 나오고, 편집도 거의 안 하고 돈 번다는 영상 많이 보이죠.",
            "body": "그 말의 핵심은 도구가 아니라 니치입니다. 사람들이 계속 보고 싶은 문제를 찾고, 그걸 반복 가능한 포맷으로 만드는 게 먼저입니다.",
            "cta": "혼자 일하는 사람을 위한 운영 진단은 CHEONOK에서 시작합니다.",
        },
        {
            "title": "AI 유튜브 자동화가 실패하는 이유",
            "hook": "AI 도구만 깔면 유튜브 수익이 난다고 생각하면 위험합니다.",
            "body": "도구는 마지막입니다. 먼저 시장, 사람의 욕망, 반복 포맷, 업로드 루프가 있어야 합니다. CHEONOK은 이 순서를 시스템으로 정리합니다.",
            "cta": "무료 운영 진단으로 지금 병목부터 확인하세요.",
        },
        {
            "title": "성실한데 도구가 없는 사람에게 필요한 것",
            "hook": "열심히 하는데 계속 제자리라면 능력 문제가 아닐 수 있습니다.",
            "body": "문제는 구조입니다. 유입, 결제, 콘텐츠, 반복 업무가 연결되지 않으면 아무리 열심히 해도 남는 게 없습니다.",
            "cta": "CHEONOK은 사람의 가치를 키우는 운영 구조를 만듭니다.",
        },
    ]


def homepage_copy(category: str):
    if category == "AI_AGENT_RUNTIME":
        return [
            "CHEONOK은 AI 도구를 나열하지 않습니다. AI가 실제로 일하는 운영 루프를 만듭니다.",
            "대표는 방향을 정하고, 시스템은 수집·분석·수정·보고를 반복합니다.",
            "작은 팀도 Runtime이 있으면 큰 조직처럼 움직일 수 있습니다.",
            "자동화보다 중요한 것은 검증 가능한 반복 구조입니다.",
        ]
    if category == "PROVEN_SYSTEM_REVERSE":
        return [
            "이미 성공한 시스템을 역추적해 불편함·고객·가격·유입 구조를 분해합니다.",
            "겉모습은 복제하지 않고, 작동 원리를 더 쉽고 인간친화적인 구조로 재설계합니다.",
        ]
    if category == "PAIN_TO_PRODUCT":
        return [
            "사람들이 돈을 내는 지점은 반복되는 불편함이 사라지는 순간입니다.",
            "CHEONOK은 불편함을 찾고, 행동 수를 줄이고, 상품 구조로 바꿉니다.",
        ]
    return [
        "얼굴을 드러내지 않아도, 거대한 자본이 없어도, 사람의 경험과 아이디어는 콘텐츠 자산이 될 수 있습니다.",
        "CHEONOK은 AI 도구를 파는 곳이 아니라, 유입·콘텐츠·결제·보고를 연결해 현실에서 돈이 도는 구조를 만듭니다.",
        "먼저 작은 수익 루프를 만들고, 반복되는 것만 자동화합니다.",
        "성실하지만 도구가 부족한 사람의 가치를 키우는 성장 운영체계를 만듭니다.",
    ]


def next_actions(category: str):
    if category == "AI_AGENT_RUNTIME":
        return [
            "Claude Code / Cursor / AI Agent / Runtime 계열 영상과 글 5개를 추가 수집한다.",
            "CHEONOK Runtime Architecture에 'AI Agent Work Loop' 섹션을 추가한다.",
            "현재 Social Signal 도구를 '수동 분석기'가 아니라 '작업 지시-검증-보고 루프'로 확장한다.",
        ]
    if category == "PROVEN_SYSTEM_REVERSE":
        return [
            "성공한 서비스 10개를 찾고 불편함·고객·가격·유입 구조를 표로 분해한다.",
            "겉모습 복제 금지, 구조 복제만 허용하는 Reverse Scout 규칙을 정본에 추가한다.",
            "CHEONOK 2등·3등 진입 후보 3개를 뽑는다.",
        ]
    if category == "PAIN_TO_PRODUCT":
        return [
            "반복 불편함 사례 20개를 Social Signal DB에 수집한다.",
            "Pain Score = 빈도 × 대중성 × 긴급성 ÷ 행동 수 공식을 적용한다.",
            "행동 수를 1회로 줄일 수 있는 상품 후보를 우선 개발한다.",
        ]
    return [
        "이 신호를 Social Signal DB에 저장한다.",
        "유사 TikTok/Shorts/Threads/YouTube를 5개 더 분석한다.",
        "반복되는 욕망이 확인되면 CHEONOK 콘텐츠 시리즈로 만든다.",
        "GitHub Scout로 관련 무료 도구를 탐색한다.",
        "홈페이지 무료진단 CTA와 연결한다.",
    ]


def main():
    if len(sys.argv) < 2:
        print("Usage: python tools/social_signal_scout_v03_analyze.py <workdir>")
        sys.exit(1)

    workdir = Path(sys.argv[1]).resolve()
    if not workdir.exists():
        print("WORKDIR_NOT_FOUND", workdir)
        sys.exit(2)

    meta = load_json(workdir / "metadata.json")
    subtitles = read_text(workdir / "subtitles_collected.txt")
    transcript = read_text(workdir / "transcript_collected.txt")
    report = read_text(workdir / "report.md")

    title = meta.get("title") or ""
    desc = meta.get("description") or ""
    uploader = meta.get("uploader") or meta.get("channel") or ""
    view_count = meta.get("view_count") or ""
    like_count = meta.get("like_count") or ""
    duration = meta.get("duration") or ""
    tags = meta.get("tags") or []

    full_text = "\n".join([title, desc, " ".join(tags if isinstance(tags, list) else []), subtitles, transcript, report])
    full_text_clean = clean_text(full_text)
    hashtags = extract_hashtags(full_text)
    signals = detect_signals(full_text_clean)
    category_code, category_label = classify_category(full_text_clean, signals)
    desires = infer_desires(category_code, signals)
    risks = risk_flags(category_code, full_text_clean)
    scripts = make_shorts_scripts(category_code)
    copy_lines = homepage_copy(category_code)
    actions = next_actions(category_code)

    if category_code in ["AI_AGENT_RUNTIME", "PROVEN_SYSTEM_REVERSE", "PAIN_TO_PRODUCT"]:
        verdict = f"PASS — strong {category_label} signal"
    elif len(signals) >= 3:
        verdict = "PASS — strong social signal"
    elif len(signals) >= 1:
        verdict = "HOLD/PASS — weak to medium signal"
    else:
        verdict = "HOLD — not enough signal"

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    md = f"""# CHEONOK Social Signal Scout v0.3 — Content Conversion Report

생성시각: {now}

## 1. 원본 요약

- title: {title}
- uploader: {uploader}
- duration: {duration}
- view_count: {view_count}
- like_count: {like_count}
- hashtags: {', '.join(hashtags) if hashtags else '-'}

## 2. 자동 분류

- category_code: **{category_code}**
- category_label: **{category_label}**

## 3. 정본 판정

판정: **{verdict}**

감지 신호:

{chr(10).join(['- ' + s for s in signals]) if signals else '- 감지 신호 부족'}

## 4. 사람들이 반응하는 원초적 욕망

{chr(10).join(['- ' + d for d in desires])}

## 5. 위험/검증 포인트

{chr(10).join(['- ' + r for r in risks])}

## 6. CHEONOK식 해석

```text
{category_interpretation(category_code)}
```

## 7. 콘텐츠 아이디어

{chr(10).join([f'{i+1}. {x}' for i, x in enumerate(content_ideas(category_code))])}

## 8. 쇼츠 대본 초안

"""

    for i, s in enumerate(scripts, 1):
        md += f"""
### SCRIPT {i}. {s['title']}

Hook:
{s['hook']}

Body:
{s['body']}

CTA:
{s['cta']}
"""

    md += """
## 9. 홈페이지 반영 문구 후보

"""
    md += "\n".join([f"- {x}" for x in copy_lines])

    md += f"""

## 10. 다음 행동

```text
{chr(10).join([f'{i+1}. {x}' for i, x in enumerate(actions)])}
```

## 11. 정본 원칙

```text
신호는 PASS 가능.
증거는 검증 전 HOLD.
겉모습 그대로 카피는 BLOCK.
불편함 해결 구조·성공 구조·운영 루프의 CHEONOK식 변환은 PASS.
```
"""

    out = workdir / "content_ideas.md"
    out.write_text(md, encoding="utf-8")
    print("CHEONOK v0.3 analyzer DONE")
    print("category:", category_code)
    print("output:", out)


if __name__ == "__main__":
    main()
