# -*- coding: utf-8 -*-
"""
CHEONOK Social Signal Scout v0.3 Analyzer
-----------------------------------------
Purpose:
- Read one Social Signal Scout workdir generated by v0.2.
- Convert metadata/subtitles/transcript into CHEONOK strategy outputs.
- No external AI API required. Rule-based first version.

Usage:
python tools/social_signal_scout_v03_analyze.py "C:/Users/USER/Desktop/CHEONOK_SOCIAL_SCOUT/data/social_signal_scout/WORKDIR"

Output:
- content_ideas.md
"""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime
from pathlib import Path


def read_text(path: Path, limit: int = 50000) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")[:limit]


def load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8", errors="replace"))
    except Exception:
        return {}


def clean_text(text: str) -> str:
    text = re.sub(r"\s+", " ", text or "").strip()
    return text


def extract_hashtags(text: str):
    return sorted(set(re.findall(r"#[A-Za-z0-9_가-힣]+", text or "")))


def detect_signals(text: str):
    low = (text or "").lower()
    rules = [
        ("현금흐름/수익", ["money", "revenue", "income", "earn", "수익", "돈", "매출", "달러", "$"]),
        ("얼굴 없는 콘텐츠", ["faceless", "no face", "without showing", "얼굴", "비대면"]),
        ("유튜브/쇼츠", ["youtube", "shorts", "short", "유튜브", "쇼츠"]),
        ("AI/자동화", ["ai", "automation", "자동화", "인공지능"]),
        ("니치 발굴", ["niche", "니치", "micro niche"]),
        ("초보자/쉬움", ["beginner", "easy", "simple", "초보", "쉽게", "편집 없이", "without editing"]),
        ("빠른 시간/단기 성과", ["90 days", "30 days", "day", "일", "개월", "fast", "quick"]),
        ("도구/소프트웨어", ["tool", "software", "app", "도구", "프로그램"]),
    ]
    found = []
    for name, keys in rules:
        if any(k in low for k in keys):
            found.append(name)
    return found


def infer_desires(signals):
    desires = []
    if "현금흐름/수익" in signals:
        desires.append("지금 돈이 도는 구조를 만들고 싶다")
    if "얼굴 없는 콘텐츠" in signals:
        desires.append("얼굴을 드러내지 않고도 콘텐츠 자산을 만들고 싶다")
    if "유튜브/쇼츠" in signals:
        desires.append("플랫폼 추천 알고리즘을 타고 반복 유입을 만들고 싶다")
    if "AI/자동화" in signals:
        desires.append("사람이 직접 다 하지 않고 AI로 시간을 줄이고 싶다")
    if "니치 발굴" in signals:
        desires.append("경쟁이 덜한 작은 시장을 찾아 빠르게 들어가고 싶다")
    if "초보자/쉬움" in signals:
        desires.append("복잡한 기술 없이 바로 시작하고 싶다")
    if not desires:
        desires.append("새로운 기회가 있는지 확인하고 싶다")
    return desires


def risk_flags(text: str):
    low = (text or "").lower()
    risks = []
    if any(k in low for k in ["$", "달러", "revenue", "income", "수익"]):
        risks.append("수익 인증은 과장 가능성이 있으므로 증거로 쓰지 말고 신호로만 사용")
    if any(k in low for k in ["one tool", "도구 하나", "without editing", "편집 없이"]):
        risks.append("도구 하나로 해결된다는 표현은 과장일 수 있음")
    if any(k in low for k in ["faceless", "얼굴"]):
        risks.append("얼굴 없는 콘텐츠는 니치·대본·유지력이 핵심이며 자동화만으로는 부족")
    if not risks:
        risks.append("원본 콘텐츠의 맥락과 저작권을 확인해야 함")
    return risks


def make_shorts_scripts(signals, desires):
    scripts = []

    scripts.append({
        "title": "얼굴 없이 돈 버는 콘텐츠, 진짜 핵심은 AI가 아닙니다",
        "hook": "얼굴 안 나오고, 편집도 거의 안 하고 돈 번다는 영상 많이 보이죠.",
        "body": "그 말의 핵심은 도구가 아니라 니치입니다. 사람들이 계속 보고 싶은 문제를 찾고, 그걸 반복 가능한 포맷으로 만드는 게 먼저입니다.",
        "cta": "혼자 일하는 사람을 위한 운영 진단은 CHEONOK에서 시작합니다."
    })

    scripts.append({
        "title": "AI 유튜브 자동화가 실패하는 이유",
        "hook": "AI 도구만 깔면 유튜브 수익이 난다고 생각하면 위험합니다.",
        "body": "도구는 마지막입니다. 먼저 시장, 사람의 욕망, 반복 포맷, 업로드 루프가 있어야 합니다. CHEONOK은 이 순서를 시스템으로 정리합니다.",
        "cta": "무료 운영 진단으로 지금 병목부터 확인하세요."
    })

    scripts.append({
        "title": "성실한데 도구가 없는 사람에게 필요한 것",
        "hook": "열심히 하는데 계속 제자리라면 능력 문제가 아닐 수 있습니다.",
        "body": "문제는 구조입니다. 유입, 결제, 콘텐츠, 반복 업무가 연결되지 않으면 아무리 열심히 해도 남는 게 없습니다.",
        "cta": "CHEONOK은 사람의 가치를 키우는 운영 구조를 만듭니다."
    })

    return scripts


def make_homepage_copy(signals):
    return [
        "얼굴을 드러내지 않아도, 거대한 자본이 없어도, 사람의 경험과 아이디어는 콘텐츠 자산이 될 수 있습니다.",
        "CHEONOK은 AI 도구를 파는 곳이 아니라, 유입·콘텐츠·결제·보고를 연결해 현실에서 돈이 도는 구조를 만듭니다.",
        "먼저 작은 수익 루프를 만들고, 반복되는 것만 자동화합니다.",
        "성실하지만 도구가 부족한 사람의 가치를 키우는 성장 운영체계를 만듭니다."
    ]


def main():
    if len(sys.argv) < 2:
        print("Usage: python tools/social_signal_scout_v03_analyze.py <workdir>")
        sys.exit(1)

    workdir = Path(sys.argv[1]).resolve()
    if not workdir.exists():
        print("WORKDIR_NOT_FOUND", workdir)
        sys.exit(2)

    meta = load_json(workdir / "metadata.json")
    subtitles = read_text(workdir / "subtitles_collected.txt")
    transcript = read_text(workdir / "transcript_collected.txt")
    report = read_text(workdir / "report.md")

    title = meta.get("title") or ""
    desc = meta.get("description") or ""
    uploader = meta.get("uploader") or meta.get("channel") or ""
    view_count = meta.get("view_count") or ""
    like_count = meta.get("like_count") or ""
    duration = meta.get("duration") or ""
    tags = meta.get("tags") or []

    full_text = "\n".join([title, desc, " ".join(tags if isinstance(tags, list) else []), subtitles, transcript, report])
    full_text_clean = clean_text(full_text)
    hashtags = extract_hashtags(full_text)
    signals = detect_signals(full_text_clean)
    desires = infer_desires(signals)
    risks = risk_flags(full_text_clean)
    scripts = make_shorts_scripts(signals, desires)
    homepage_copy = make_homepage_copy(signals)

    if len(signals) >= 3:
        verdict = "PASS — strong social signal"
    elif len(signals) >= 1:
        verdict = "HOLD/PASS — weak to medium signal"
    else:
        verdict = "HOLD — not enough signal"

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    md = f"""# CHEONOK Social Signal Scout v0.3 — Content Conversion Report

생성시각: {now}

## 1. 원본 요약

- title: {title}
- uploader: {uploader}
- duration: {duration}
- view_count: {view_count}
- like_count: {like_count}
- hashtags: {', '.join(hashtags) if hashtags else '-'}

## 2. 정본 판정

판정: **{verdict}**

감지 신호:

{chr(10).join(['- ' + s for s in signals]) if signals else '- 감지 신호 부족'}

## 3. 사람들이 반응하는 원초적 욕망

{chr(10).join(['- ' + d for d in desires])}

## 4. 위험/검증 포인트

{chr(10).join(['- ' + r for r in risks])}

## 5. CHEONOK식 해석

```text
이 콘텐츠의 본질은 단순히 "AI 도구 하나로 돈 벌기"가 아니다.
본질은 "얼굴을 드러내지 않아도, 복잡한 편집을 몰라도,
AI와 니치 전략을 통해 콘텐츠 자산을 만들고 싶은 욕망"이다.

CHEONOK은 이것을 과장 수익 메시지로 쓰지 않고,
성실하지만 도구가 부족한 사람이 유입·콘텐츠·결제·보고 구조를 갖추도록 돕는 방향으로 변환한다.
```

## 6. 콘텐츠 아이디어

1. 얼굴 없이도 시작할 수 있는 콘텐츠 사업의 진짜 핵심
2. AI 유튜브 자동화가 실패하는 이유
3. 도구 하나보다 중요한 것은 니치와 반복 포맷이다
4. 혼자 일하는 사람이 콘텐츠 자산을 만드는 법
5. 성실하지만 도구가 없는 사람을 위한 운영 구조

## 7. 쇼츠 대본 초안 3개

"""

    for i, s in enumerate(scripts, 1):
        md += f"""
### SCRIPT {i}. {s['title']}

Hook:
{s['hook']}

Body:
{s['body']}

CTA:
{s['cta']}
"""

    md += """
## 8. 홈페이지 반영 문구 후보

"""
    md += "\n".join([f"- {x}" for x in homepage_copy])

    md += f"""

## 9. 다음 행동

```text
1. 이 신호를 Social Signal DB에 저장한다.
2. 유사 TikTok/Shorts를 5개 더 분석한다.
3. 반복되는 욕망이 확인되면 CHEONOK 콘텐츠 시리즈로 만든다.
4. GitHub Scout로 관련 무료 도구를 탐색한다.
5. 홈페이지 무료진단 CTA와 연결한다.
```

## 10. 정본 원칙

```text
신호는 PASS 가능.
수익 증거는 검증 전 HOLD.
그대로 베끼기는 BLOCK.
CHEONOK식 변환은 PASS.
```
"""

    out = workdir / "content_ideas.md"
    out.write_text(md, encoding="utf-8")
    print("CHEONOK v0.3 analyzer DONE")
    print("output:", out)


if __name__ == "__main__":
    main()
